### ISSUE TITLE
Page links not show in html source code

### ISSUE THREAD

**Issue by tuanla6** [etchteam/next-pagination#12]
I view the html source code, but I don't see all pages link. How to make it show all links on html source for better SEO. Thank you

**Comment by gavmck** [comment]
This component doesn't currently include all the links, only a few selected ones. If there were, say, 1000 pages that would be a lot of HTML!

You could add a prop t make it render all of them. PRs welcome!

**Comment by tuanla6** [comment]
Thanks @gavmck
