### ISSUE TITLE
Customize the UI of next-pagination

### ISSUE THREAD

**Issue by Gundetiakki** [etchteam/next-pagination#16]
can i get a overview of how can i customize the UI of next-pagination for eg I want to customize the arrows for the links here 

![sample](https://user-images.githubusercontent.com/30874150/129854330-9b88bce1-8cb6-4cf5-85eb-783a0d2106e0.PNG)

and also i want to remove per page label as shown and want to add show in the dropdown like show 10,show 20 something like that 
can you help me with this please 
Thank you

**Comment by gavmck** [comment]
You can customise the styles of the UI by passing in a SCSS file as detailed in the readme: https://github.com/etchteam/next-pagination#theming

It sounds like you should be able to achieve the bits you want with a little bit of clever CSS.

**Comment by Gundetiakki** [comment]
okay thanks for the comment but actually I'm new to nextjs ill try that but also can you just help with the api part as well please because my ui is not connected to the actual data so if you can help me on that too

**Comment by gavmck** [comment]
That'll depend on your API I'm afraid, it's not specific to Next.
