### ISSUE TITLE
Dynamic Routes: next/link pagination issue

### ISSUE THREAD

**Issue by WEEFAA** [etchteam/next-pagination#22]
#4 

Suggested fix.

Introduce a prop called linkProps (LinkProps from next/link). 

Suggested Keys:
- as: string
- scroll: bool // this can solve this [issue](https://github.com/etchteam/next-pagination/issues/17#issue-974032218)

File: /[my-dynamic-router].js
Assume that the dynamic route value is "javascript" 
```javascriptreact
 <Pagination total={100} linkProps={{ as: "/javascript", scroll: false }}/>
```
_"href" is a file system path used by the page and it shouldn't change at runtime. "as" on the other hand, will be dynamic most of the time according to your needs._

```next-pagination``` link tags should be reflected as expected.

![image](https://user-images.githubusercontent.com/26353887/142751169-2118229b-84b8-4384-bbec-6a862704d6f9.png)

It uses the same API as next/link, [previous docs](https://nextjs.org/docs/tag/v9.5.2/api-reference/next/link#dynamic-routes)

I've managed to solve the problem on my custom pagination component. I might request a PR soon as well, not really sure about that.

**Comment by gavmck** [comment]
We've added linkProps to the component so this should work now. Thanks!
