### ISSUE TITLE
URL Parameter Placeholder for dynamic routes not replaced 

### ISSUE THREAD

**Issue by WEEFAA** [etchteam/next-pagination#4]
Pagination pages redirect links are not properly process to sustain how NextJS handles dynamic routes

![Bug](https://user-images.githubusercontent.com/26353887/90858352-9a462f80-e3b8-11ea-9a7a-e7f3a48b44a5.png)

It seems that the [tag_slug] just need to be replaced by its value passed on url query[tag_slug] and remove it from the query parameter permanently to have a more cleaner url for each pagination.

**Comment by gavmck** [comment]
Why are you using `blogs/tag/[tag_slug]` and not `/blogs/tag/javascript`?

How did tag_slug end up in the query params?

**Comment by WEEFAA** [comment]
How to replicate: 

1. Create a dynamic route/page (```[tag_slug].tsx``` in my case, under _pages/blogs/tag/_ )
2. Implement ```next-pagination``` on that page (```[your_dynamic_page].tsx```) 
3. Go to the next/prev page 

Result: broken url 

![image](https://user-images.githubusercontent.com/26353887/91178807-4620af80-e718-11ea-91e2-7c4b012b7483.png)

**Comment by gavmck** [comment]
Thanks! I've managed to get a similar issue although mine never replaces the url with the dynamic path `[foo]`.

Will take a look for you.

**Comment by gavmck** [comment]
This issue should now be fixed I think, please re-open if not.

**Comment by WEEFAA** [comment]
It looks like that the issue is not resolve yet.

This is an example of the URL generated from [DEMO](https://etchteam.github.io/next-pagination/dynamic-test) 
https://etchteam.github.io/next-pagination?dynamic=dynamic-test&page=2

**Comment by WEEFAA** [comment]
Suggested fix.

Introduce a prop called linkProps (LinkProps from next/link). 

Suggested Keys:
- as: string
- scroll: bool // this can solve this [issue](https://github.com/etchteam/next-pagination/issues/17#issue-974032218)

File: /[my-dynamic-router].js
Assume that dynamic route value is "javascript" 
```javascriptreact
 <Pagination total={100} linkProps={{ as: "/javascript", scroll: false }}/>
```
_"href" is a file system path used by the page and it shouldn't change at runtime. "as" on the other hand, will be dynamic most of the time according to your needs._

It uses the same API as next/link, [previous docs](https://nextjs.org/docs/tag/v9.5.2/api-reference/next/link#dynamic-routes)

I've managed to solve the problem on my custom pagination component. I might request a PR soon as well, not really sure about that.

**Comment by WEEFAA** [comment]
New ```next-pagination``` link tags should be updated as well.

![image](https://user-images.githubusercontent.com/26353887/142751064-1617c35f-ae14-41ed-a9e3-368e44cc351b.png)

**Comment by gavmck** [comment]
> It looks like that the issue is not resolve yet.
> 
> This is an example of the URL generated from [DEMO](https://etchteam.github.io/next-pagination), Dynamic routing example. https://etchteam.github.io/next-pagination?dynamic=dynamic-test&page=2

Ah sorry I forgot to deploy the example!

**Comment by WEEFAA** [comment]
This is awesome, thanks! 👏
