### ISSUE TITLE
Synchronize multiple pagination components

### ISSUE THREAD

**Issue by phdoerfler** [etchteam/next-pagination#44]
Is there a way to synchronize multiple pagination components?
I got a website with two pagination components:
![image](https://user-images.githubusercontent.com/163428/164221974-63d28f9e-2a85-4f6a-b1bb-dcc9ee64b6fe.png)

Changing the page size in one of them (here: the top one) does not update the other one:
![image](https://user-images.githubusercontent.com/163428/164222360-1fc1a820-136d-4597-9f94-3d606632f68a.png)
Note how the query parameter, as well as the page size dropdown that was just used, correctly shows the page size.

I'm not enough into next and react to hazard a guess or even a PR as to how this might be doable.

**Comment by gavmck** [comment]
So, React will not re-render the whole page when the route changes, it will just pass new data to the components.
We only set defaultValue on the select so it doesn't update after the initial render, using [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html).

I've pushed a fix on `3.5.2` that should solve the bug for you :)

**Comment by phdoerfler** [comment]
It does! Thanks a lot, that was fast! Good to know that specifying the `key` solves the issue.

**Comment by gavmck** [comment]
`key` param forces a complete reconstruction when the value of `key` changes. Or you can use it to force it to _not_ reconstruct/rerender which can be useful when animating components in and out.

We should probably switch to a controlled select, but this will get you going where you want to be for now.

**Comment by phdoerfler** [comment]
It does! I appreciate the pace :) I got feedback from a team member and they're very happy with the result and that's to no small part thanks to this library! In case you're wondering, it's for a FabLab in Germany, a public workshop open to everyone and this app will be used for the self-checkout, replacing an old, PyQt based solution.

**Comment by gavmck** [comment]
Awesome, would love to see it when it goes live.
