### ISSUE TITLE
turn OFF the `Per Page` Dropdown and text

### ISSUE THREAD

**Issue by VinylVault** [etchteam/next-pagination#68]
Hi, 

I want to be able to set the number per page as a specific number and not have visitors change the option, is there a way I can do that?

Thanks in advance, and thanks for creating a fantastic component :D  

Dex

**Comment by LeonneBrito** [comment]
Although it is an old issue, I have just created a PR that adds this possibility.

**Comment by gavmck** [comment]
If you can't change the option then it's better to remove the control. You should be able to set the default and then hide it away with CSS.
