### ISSUE TITLE
Label 'per page' in another language

### ISSUE THREAD

**Issue by uubuz** [etchteam/next-pagination#7]
There is a chance for different language versions? The per page label is English only

**Comment by gavmck** [comment]
Sure thing, PRs welcome! Or I can take a look in a couple of weeks.

**Comment by phdoerfler** [comment]
I, too, would appreciate being able to customize the text shown to the user. I'm working on a small webapp for a German non-profit and the English pagination text is sticking out like a sore thumb. Otherwise the component is really nice, I appreciate the work that went into it!

**Comment by gavmck** [comment]
Out on `3.3.0`
